name: codeClimate

# Trigger the workflow on push or pull request
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      # Node versions list
      matrix:
        node-version: [20.x]

    steps:
        - uses: actions/checkout@v4
        - name: Run-test
          run: make lint